name: Current test status
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reppository code
        uses: actions/checkout@v2

      - name: Run all tests
        run: python -m unittest tests.py
      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_TOKEN }}
          status: ${{ job.status }}
